# -*- coding: utf-8 -*-
"""Day3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15Ssr8HNYyFiGSfnbcY5paT4FTRzJG_aa
"""

# While loop
spam=0
if spam<=5:
  print("hello world")
  spam += 1

spam=0
while spam<5:
  print("hello world")
  spam += 1

name = ""
while name != 'Datta':
    print("Please type your name")
    name = input('>')

    print('Thank you')

name = ""
while name != 'Datta':
    print("Please type your name")
    name = input('>')
    break
print('Thank you')

for num in range(10):
  if num%2==0:
    continue
    Print(num)

#Break:stop the loop
#Continue:skip some part of iteration

for num in range(10):
  if num%2==0:
    continue
    Print(num)

# for loop

for i in range(5):
  print("hello")

#range(stop)

for i in range(5):
  print(i)

#range(,start,stop)

for i in range(0,5):
  print(i)

#range (start,stop,step)
for i in range(0,10,3):
  print(i)

total=0
for i in range(101):
  total = total+i
  print(total)


  '''
  Module:Contains pre-written code
  '''

# 1)random Module

import random
random.randint(1,10)


# 2) sys Module - Can communicattion with computer System

#3) os Mudule -  Can talk with os and connects folder and file

# 4) math Module

#module name .

import sys

while True:
  print('Type to exit')
  response = input('>')
  if response =='exit':
    sys.exit()
    Print('you typed' + response + '.')

#Mini Project


# This is a guess the number game.
import random
secret_number = random.randint(1, 20)

print('I am thinking of a number between 1 and 20.')

# Ask the player to guess 6 times.
for guesses_taken in range(1, 7):
    print('Take a guess.')
    guess = int(input('>'))
    if guess < secret_number:
        print('Your guess is too low.')
    elif guess > secret_number:
        print('Your guess is too high.')
    else:
        break # This condition is the correct guess!

if guess == secret_number:
       print('Good job! You got it in ' + str(guesses_taken) + ' guesses!')
else:
    print('Nope. The number was ' + str(secret_number))
