# -*- coding: utf-8 -*-
"""Pytorchfundamentals.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-kFvv6L00QS5hNshm-SGY3lZztO3ogDo

**PyTorch Fundamentals**
1. What is PyTorch?
- PyTorch is an open source machine learning and deep learning framework.


2. What can PyTorch be used for?
- PyTorch allows you to manipulate and process data and write machine learning algorithms using Python code
"""

#Importing PyTorch

import torch
torch.__version__


#notes :
'''Tensor : Tensors are the fundamental building block of machine learning.

Their job is to represent data in a numerical way.'''

#Creating tensors : use torch.Tensor class
#1. A scalar is a single number and in tensor-speak it's a zero dimension tensor.


#scalar
scalar = torch.tensor(100)
scalar

scalar.ndim     #We can check the dimensions of a tensor using the ndim attribute.

# Get the Python number within a tensor (only works with one-element tensors)
scalar.item()

# 2. vector :A vector is a single dimension tensor but can contain many numbers.

vector = torch.tensor([4,7])
vector

# Check the number of dimensions of vector
vector.ndim       #You can tell the number of dimensions a tensor in PyTorch has by the number of square brackets on the outside ([) and you only need to count one side.

# Check shape of vector
#Shape : Another important concept for tensors is their shape attribute. The shape tells you how the elements inside them are arranged.

vector.shape

# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

# Check number of dimensions
MATRIX.ndim

MATRIX.shape

#3. How about we create a tensor?

TENSOR = torch.tensor([[[2,5,3],
                        [6,5,3],
                        [5,7,5]]])
TENSOR

# Check number of dimensions
TENSOR.ndim

# Check shape of TENSOR
TENSOR.shape

