# -*- coding: utf-8 -*-
"""Timed_Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zuuc_yXuGqw8nJ7Ak4CsHLY5ZpSHFdrX
"""

#Q. 1 Even or Odd

# List of numbers to check
numbers = [12, 7, 9, 4, 22, 15, 8, 3, 30, 11]

# Counters to keep track of even and odd numbers
even_count = 0
odd_count = 0

# Loop through each number in the list
for number in numbers:
  if (number % 2 == 0):
    print("Number is even :",number)
    even_count += 1

  else:
    print("Number is odd :",number)
    odd_count += 1

# Print the final counts after the loop finishes
print("even_count :",even_count)
print("odd_count :",odd_count)

#Q2. Average Calculator
def calculate_average(numbers:list)->float:
 try:

    # Calculate average by summing all numbers and dividing by count
    return sum(numbers)/len(numbers)
 except ZeroDivisionError:
    print("cannot divide by zero")

print(calculate_average([10,20,30]))
print(calculate_average([]))

#Q. 3 Number Guessing

import random as rd

# List to store all the random guesses generated
guesses = []

# Generate 10 random guesses between 1 and 50
for i in range(10):
    guess = rd.randint(1, 50)
    guesses.append(guess)
    print("Guess:", guess)

# Find the highest value among all the guesses
highest = max(guesses)
# Calculate the average of all guesses, rounded to 2 decimal places
average = round(sum(guesses) / len(guesses), 2)

print("Highest guess:", highest)
print("Average guess:", average)

#Q. 4 use Student Class

class Student:
    def __init__(self, name: str, marks: list):   #Initialize a Student with a name and a list of marks.

        self.name = name
        self.marks = marks

    def average(self):
        total = sum(self.marks)
        count = len(self.marks)
        avg = total / count
        return avg

    def __str__(self):

        return f"{self.name}: average {self.average():.1f}"


# Driver code

students = [
   Student("Datta", [78, 80, 82]),
    Student("Raj", [70, 85, 88]),
    Student("Adi", [91, 99, 88])
]

for student in students:
    print(student)

#Q. 5 Import and Use a Module

import random

rolls = 0
number = 0

# random.randint(1, 6) simulates rolling a 6-sided die
while number != 6:
    number = random.randint(1, 6)
    rolls += 1
    print("Rolled:", number)

print("It took", rolls, "rolls to get a 6")