# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14wVM7aJNPrKg0wcbXEIkT3-zwbNmTHpZ
"""

#ZeroDivisionError Example
def Zero_division(a, b):
    try:
        return a / b
    except ZeroDivisionError:
        print("can't divide by zero")

n1 = int(input("Enter first number: "))
n2 = int(input("Enter second number: "))

print(Zero_division(n1, n2))

#Value Error Exampole
def value_error():
    try:
        num = int(input("Enter number: "))
        print("VAlue:", num)

    except ValueError:
        print("Enter valid number")


value_error()

#Type Error Example
def type_error():
    try:
        total = "Score: " + 100
        print(total)

    except TypeError:
        print("Can't add int and string.")


type_error()